{"uuid": "902a43fc-0c3c-467c-9336-3f225083badd", "children": ["956661a1-57d6-455a-8090-345ffa259915"], "befores": [{"name": "setup", "status": "failed", "statusDetails": {"message": "AssertionError: User is not authorized\n", "trace": "  File \"/home/dan/home/programming/projects/task_test_automation_github_project/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/dan/home/programming/projects/task_test_automation_github_project/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/dan/home/programming/projects/task_test_automation_github_project/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/dan/home/programming/projects/task_test_automation_github_project/test_main_page.py\", line 26, in setup\n    main_page.should_be_authorized_user()\n  File \"/home/dan/home/programming/projects/task_test_automation_github_project/pages/main_page.py\", line 19, in should_be_authorized_user\n    assert False, \"User is not authorized\"\n"}, "attachments": [{"name": "User is not authorized", "source": "5116ebf9-eab9-4048-a6b5-6abea5a18691-attachment.png", "type": "image/png"}], "start": 1637926451058, "stop": 1637926464925}], "start": 1637926451058, "stop": 1637926464948}