{"uuid": "9be56298-7139-4ca5-9961-fa46e3f7fcf4", "children": ["c1edc25c-c25b-463f-ab48-fd3626cd305d"], "befores": [{"name": "setup", "status": "failed", "statusDetails": {"message": "AssertionError: User is not authorized\n", "trace": "  File \"/home/dan/home/programming/projects/task_test_automation_github_project/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/dan/home/programming/projects/task_test_automation_github_project/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/dan/home/programming/projects/task_test_automation_github_project/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/dan/home/programming/projects/task_test_automation_github_project/test_main_page.py\", line 26, in setup\n    main_page.should_be_authorized_user()\n  File \"/home/dan/home/programming/projects/task_test_automation_github_project/pages/main_page.py\", line 19, in should_be_authorized_user\n    assert False, \"User is not authorized\"\n"}, "attachments": [{"name": "User is not authorized", "source": "f7d93e3a-ebda-44c6-ba29-20f17b230ba5-attachment.png", "type": "image/png"}], "start": 1637926405390, "stop": 1637926418925}], "start": 1637926405390, "stop": 1637926418959}